### ISSUE TITLE
frontViewController 프로퍼티 main thread 관련 warning

### ISSUE THREAD

**Issue by magi82** [yoonhg84/RxModalityStack#3]
present 했을때 

```
    public var frontViewController: UIViewController? {
        return stack.last?.viewController ?? UIApplication.shared.keyWindow?.rootViewController
    }
```
이부분에서 main thread 관련 warning이 뜹니다.

<img width="935" alt="2018-03-11 11 13 04" src="https://user-images.githubusercontent.com/8379861/37248824-53b2e0aa-251e-11e8-8bac-b210b814278a.png">

**Comment by yoonhg84** [comment]
수정했습니다.
